language: ruby
rvm: 2.3.3
cache:
  bundler: true
  directories:
  - node_modules
branches:
  only:
  - master
before_install:
- nvm install 7.4.0
install:
- npm install
- bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
before_script:
- git config --global user.name "hnbot"
- git config --global user.email "nygrenh+hnbot@gmail.com"
- export COMMIT_MESSAGE=Update:\ $(git log -1 --pretty=%s)
- git clone -b gh-pages --single-branch https://github.com/materiaalit/tikape-s17.git
  build
script:
- bundle exec middleman build
after_success:
- cd build
- git checkout HEAD README.md .github
- git add --all
- git commit -m "$COMMIT_MESSAGE"
- git push "https://hnbot:$GITHUB_API_KEY@github.com/materiaalit/tikape-s17.git" gh-pages:gh-pages
  2>&1 | sed "s/$GITHUB_API_KEY/<confidential>/g"
env:
  global:
    secure: CkUTL7jrK1qCDk+TkHmQ5lNHDVoD4wUJzcq7Y747jnaSDI2UYOf9FBtY21xDaaC+ujmz1HaIrNAJPl0BxEDXm4WYTuL8FHbh7CpG82cn6Nqlgg+fDhXEVFoAHCcx8q15HXI7yMD7fKDP+PKwOXQkd56Y+UDDSTjT6JiSeMrolttmHhqQNJnFZYvOs/qjk5XfIwg1e9dQDOrhPt7z+N3iNPLhzJ8y1nTyo3LuuNc8CKSynlHit/XDn5fUFnh8f5zFFlekdFti0AnYs+Z4IH7In+Qaa9HiQ7rNKA8pn5yXbQ1YwbYekJua5nUaGifUSqqYhgFp6TdOxqIPrlF0AV2ubN0kP4Kpwe1uHoQHMS7gsFj26bkY/VjSYjJc+MrsvuBMNB/lpV90TBPNnXcLT8Slz80xZJ6Jci5VqnCNSG/RRmAV2Y1LAu9kkT2g4PR1mSnMYwmGbHU3d3AtCUmN9LNUu+pFicXZCeMmKfxbZYkZLAVIflKRS9yErxkEr4A6/bOw95bc77tAGBVuuZaYdDgt6dG/DscuwcUaR2ojtXoZxqgeF6n8YT/sNKkEZumGLWuBC2j+jtYimJazIQOyMtszIJh0suBkfgoDu3fvjjBMjCEIyT7XhA2JVvqMKuh/n+1DZ+iHtF7v5s98bcTITN8H1Krb4csfwdxoCYEZPznNeKI=
